# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Installs dependencies
      - name: Install remark dependencies
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json

      # Run markdown lint and save the report
      - name: Run markdown lint
        run: |
          npx remark . --use remark-preset-lint-consistent --reporter vfile-reporter-json > remark-lint-report.json

      # Uploads the lint report as an artifact
      - name: Upload remark lint report
        uses: actions/upload-artifact@v2
        with:
          name: remark-lint-report
          path: remark-lint-report.json
